# Problem 1

In [2]:
from numpy import *

class pcn:
    #""" A basic Perceptron (the same pcn.py except with the weights printed
    #and it does not reorder the inputs)"""

    def __init__(self,inputs,targets):
       # """ Constructor """
        # Set up network size
        if ndim(inputs)>1:
            self.nIn = shape(inputs)[1]
        else: 
            self.nIn = 1

        if ndim(targets)>1:
            self.nOut = shape(targets)[1]
        else:
            self.nOut = 1

        self.nData = shape(inputs)[0]

        # Initialise network
        self.weights = random.rand(self.nIn+1,self.nOut)*0.1-0.05

    def pcntrain(self,inputs,targets,eta,nIterations):
       # """ Train the thing """	
        # Add the inputs that match the bias node
        inputs = concatenate((inputs,-ones((self.nData,1))),axis=1)

        # Training
        change = range(self.nData)

        for n in range(nIterations):

            self.outputs = self.pcnfwd(inputs);
            self.weights += eta*dot(transpose(inputs),targets-self.outputs)
            print ("Iteration: ", n)
            print (self.weights)

            activations = self.pcnfwd(inputs)
            print ("Final outputs are:")
            print (activations)
        #return self.weights

    def pcnfwd(self,inputs):
        #""" Run the network forward """

        outputs =  dot(inputs,self.weights)
        outputs *= 6

        #Changed the 3rd element
        return where(outputs>.333,1,0)


    def confmat(self,inputs,targets):
        """Confusion matrix"""

        # Add the inputs that match the bias node
        inputs = concatenate((inputs,-ones((self.nData,1))),axis=1)
        outputs = dot(inputs,self.weights)

        nClasses = shape(targets)[1]

        if nClasses==1:
            nClasses = 2
            outputs = where(outputs>0,1,0)
        else:
            # 1-of-N encoding
            outputs = argmax(outputs,1)
            targets = argmax(targets,1)

        cm = zeros((nClasses,nClasses))
        for i in range(nClasses):
            for j in range(nClasses):
                cm[i,j] = sum(where(outputs==i,1,0)*where(targets==j,1,0))

        print (cm)
        print (trace(cm)/sum(cm))
        
        
import numpy as np
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
targets = np.array([[0],[1],[1],[1]])

p = pcn(inputs, targets)
p.pcntrain(inputs, targets, 0.1, 6)



Iteration:  0
[[ 0.02185476]
 [ 0.10580907]
 [-0.14051814]]
Final outputs are:
[[1]
 [1]
 [1]
 [1]]
Iteration:  1
[[ 0.02185476]
 [ 0.10580907]
 [-0.04051814]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  2
[[ 0.02185476]
 [ 0.10580907]
 [-0.04051814]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  3
[[ 0.02185476]
 [ 0.10580907]
 [-0.04051814]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  4
[[ 0.02185476]
 [ 0.10580907]
 [-0.04051814]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  5
[[ 0.02185476]
 [ 0.10580907]
 [-0.04051814]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]


# Problem 2

In [16]:
#Tuition is independent var
#Salary is dependent var

#from sklearn.linear_model import LinearRegression
#didn't use sklearn

import numpy as np



x = np.array([28540, 40133, 39900, 0, 0, 42050, 43220, 39565, 40400, 54506]).reshape((-1, 1))
y = np.array([137, 135, 127, 122, 120, 118, 118, 117, 117, 114])

x_new = np.array([28540, 40133, 39900, 42050, 43220, 39565, 40400, 54506]).reshape((-1, 1))
y_new = np.array([137, 135, 127, 118, 118, 117, 117, 114])

#print(x)
#print(y)

def linreg(inputs, targets):
    inputs = np.concatenate((inputs, -np.ones((np.shape(inputs)[0],1))),axis = 1)
    beta = np.dot(np.dot(np.linalg.inv(np.dot(np.transpose(inputs),inputs)), np.transpose(inputs)),targets)
    outputs = np.dot(inputs,beta)
    #print(shape(beta))
    print('Predicted Outputs: ', outputs)
    print('Beta: ', beta)
    return beta


#model = LinearRegression()
#model.fit(x, y)
#model = LinearRegression().fit(x, y)
#r_sq = model.score(x, y)

print('Including the two schools that are free:')
print(linreg(x,y))
#print('coefficient of determination (with two free schools):', r_sq)
#print('intercept (with two free schools):', model.intercept_)
#print('slope (with two free schools):', model.coef_)
#y_pred = y_pred = model.intercept_ + model.coef_ * x
#print('predicted response (with two free schools):', y_pred, sep='\n')

print('---------------------------------')
print('Without the two schools that are free:')

print(linreg(x_new,y_new))

#model.fit(x_new, y_new)
#model = LinearRegression().fit(x_new, y_new)
#r_sq = model.score(x_new, y_new)
#print('coefficient of determination:', r_sq)
#print('intercept:', model.intercept_)
#print('slope:', model.coef_)
#y_pred = y_pred = model.intercept_ + model.coef_ * x_new
#print('predicted response:', y_pred, sep='\n')






Including the two schools that are free:
Predicted Outputs:  [122.77047616 122.03979849 122.05448389 124.56928069 124.56928069
 121.91897479 121.84523263 122.0755981  122.02297015 121.13390439]
Beta:  [-6.30274887e-05 -1.24569281e+02]
[-6.30274887e-05 -1.24569281e+02]
---------------------------------
Without the two schools that are free:
Predicted Outputs:  [134.18328839 123.6949001  123.90569925 121.96055693 120.90203763
 124.20877956 123.45334057 110.69139757]
Beta:  [-9.04717354e-04 -1.60003922e+02]
[-9.04717354e-04 -1.60003922e+02]


# Results (problem 2):
If we remove both schools with a free tuition, we get a new slope of y=-0.000904x (calulcated), correlation coefficient of .71 (calculated), and coefficient of determinism of .50976 (calculated). Because of this, we can say that there is a fairly strong linear association between tuition costs and salaries. It predicted much better without the two schools, meaning they are outliers. 

----------------------------------------------------------------------------------------------------------------------

# Problem 3

Check attached image

----------------------------------------------------------------------------------------------------------------------

# Problem 4 

## a) 
Yes I'd use supervised learning. I can use the existing data as training data 
for my new model, which will use regression. Split the dates up (of power consumption) into month and day for the input. I'll use my old data to find a slope, and 
have it predict new values based on the model that fits the slope. I could also use the demand of the next 5 days as the target outputs and make a linear actuvation function for the output. Another parameter could be consumption based on location.


## b) 
You would be able to integrate it into your data and have it further improve the 
accuracy of calculations and predictions. It could be predicted that when weather is 
good, there is less consumption of power, and when it is bad there is more. It could be
another input node included in the initial prediction.


## c) 
It would work well in 'normal' areas, and most likely predict correctly for most places. 
But there are areas where this MLP would fail; such as a newly built power plant, newly built
office buildings, farmlands, and changes in the geographical features of the land.  

----------------------------------------------------------------------------------------------------------------------

# Problem 5

This MLP will have 5 inputs and 1 bias (arbitrary number), so 5 total inputs. Inputs would consist of number of people in the ward per week, the average temp at night, the average temp during the day, the season, whether or not there is an epidemic, and the bias. The number of hidden neurons in the hidden layer will amount to 1/10 multiplied by the number of epochs. This (the number of hidden nodes) was caluclated based off of the formula (posted below) learned in class. The number of epochs would be equal to 5 years, so either 260 weeks, 60 months, or 1820 days (5 wouldn't be large enough.) We chose 5 years because of the data collection time frame. We will need to preprocess any numeric data to standardize it (hrough normalization) and make sure it is numerically consistent. I would expect this MLP to work because of the structure of the network and the data given.


Formula for calculation of number of hidden nodes: (x+b) * k + 1 * k = 1/10(N)
   
    x = # of inputs
    b = bias
    k = # of neurons
    N = epochs




----------------------------------------------------------------------------------------------------------------------

# Problem 6

## 1)
   1. Orange
   2. Red
   3. Red
   
If all of the neighbors in the plot have the same weight, the point 'U' would be classified as Red. This is because the three closest points to 'U' include one orange point, and two red points.
    

## 2)

## formula = sqrrt((y2-y1)^2 + (x2-x1))
## Applied Euclidean:
- red1 = sqrrt((2-4)^2 + (1-1)^2) = sqrrt(4)
- red2 = sqrrt((6-4)^2 + (2-1)^2) = sqrrt(5)
- orange1 = sqrrt((5-4)^2 + (2-1)^2) = sqrrt(2)

## Then take inverse square:
- 1/(red1+red2)^2 = 1/9
- 1/(orange1)^2 = 1/2

1/2 > 1/9


If the vote is made according to the inverse square of distantce, the prediction will be orange. This is because when you run the distances through the euclidean algorithm, then take the inverse square of them, you get 1/2 for orange and 1/9 for red. Because the orange value is bigger than red, it is classified as orange.